### ISSUE TITLE
An error in events.js:85 throw er; 

### ISSUE THREAD

**Issue by kibershmiber** [enricostara/termgram#3]
Hi enricostara ! Thank you for work.

Can you tell me why on my Ubuntu 15 and Node 0.12 termgram are throwing an error below:

![selection_004](https://cloud.githubusercontent.com/assets/3364472/7554398/838c64b4-f730-11e4-8d9d-543e300ac1dd.jpg)

**Comment by enricostara** [comment]
Currently, the app tries to write some logs under a log/ dir under the installation path.
I'll change this, in the meanwhile  you can grant write permission to the app on the installation folder.

**Comment by kibershmiber** [comment]
Thanks for response. I think maybe I did something wrong on install steps... I just have installed the telegram.link end termgram by instruction throw npm, than run $ termgram under my user end root. That's all what I did, maybe I forgot some steps?

**Comment by enricostara** [comment]
I double-checked the exception, please create the 'log' folder in your home as workaround, I'll fix the problem asap. Let me know

**Comment by kibershmiber** [comment]
Yes, I have created  log folder in my ~./ and all looks good. Thank you!

![selection_006](https://cloud.githubusercontent.com/assets/3364472/7560473/2717506c-f7cc-11e4-95ef-e9a680e2b30e.jpg)

**Comment by enricostara** [comment]
I changed the application setup, now a `.termgram` folder is created under the user home and also a `.termgram\log` subfolder to contain the application debug messages

**Comment by kibershmiber** [comment]
Thanks!
