### ISSUE TITLE
How the program work?

### ISSUE THREAD

**Issue by kibershmiber** [enricostara/termgram#4]
Sorry, but I really confusing. I run termgram and followed the instruction ask my login, pass and phone number. As a result I have got a message such as: "nothing to do". My question is - what the program does ?  
![riko rikoonrails _007](https://cloud.githubusercontent.com/assets/3364472/7565068/6f03e6d2-f7f5-11e4-83b6-7337857ce059.jpg)

**Comment by enricostara** [comment]
As stated in the readme file, the main purpose is provide a best practice how to develop an app using the [telegram.link](www.telegram.link) project.
Since that the api library is not yet completed, this application is only in the early stage.

**Comment by kibershmiber** [comment]
Many thanks!
